// npm run db:erd — regenerates docs/database-erd.md (Mermaid ER diagrams, one per schema) from the live database.
// Run it after every migration so the diagram never drifts from the real schema.
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import pg from 'pg';
import { pgConfig } from '../lib/env.mjs';
import { ROOT } from '../lib/paths.mjs';

const SCHEMAS = ['core', 'compliance', 'fx', 'payments', 'ledger', 'notify', 'audit'];
const OWNERS = {
  core: 'identity-service + transfer-service (Module 1)', compliance: 'compliance-service (Module 2)', fx: 'fx-service (Module 3)',
  payments: 'payment-service (Module 3)', ledger: 'ledger-service (Module 3)', notify: 'notification-service (Module 4)',
  audit: 'shared — every service inserts, nobody updates',
};

const client = new pg.Client(pgConfig('migrator'));
await client.connect();

const { rows: columns } = await client.query(
  `SELECT c.table_schema, c.table_name, c.column_name, c.data_type, c.udt_name, c.is_nullable,
          EXISTS (SELECT 1 FROM information_schema.table_constraints tc
                    JOIN information_schema.key_column_usage k USING (constraint_schema, constraint_name)
                   WHERE tc.constraint_type = 'PRIMARY KEY' AND k.table_schema = c.table_schema
                     AND k.table_name = c.table_name AND k.column_name = c.column_name) AS is_pk
     FROM information_schema.columns c
     JOIN information_schema.tables t USING (table_schema, table_name)
    WHERE c.table_schema = ANY($1) AND t.table_type = 'BASE TABLE'
    ORDER BY c.table_schema, c.table_name, c.ordinal_position`,
  [SCHEMAS],
);
const { rows: fks } = await client.query(
  `SELECT DISTINCT src_ns.nspname AS src_schema, src.relname AS src_table, dst_ns.nspname AS dst_schema, dst.relname AS dst_table,
          (SELECT string_agg(a.attname, ', ') FROM unnest(con.conkey) k JOIN pg_attribute a ON a.attrelid = con.conrelid AND a.attnum = k) AS cols
     FROM pg_constraint con
     JOIN pg_class src ON src.oid = con.conrelid JOIN pg_namespace src_ns ON src_ns.oid = src.relnamespace
     JOIN pg_class dst ON dst.oid = con.confrelid JOIN pg_namespace dst_ns ON dst_ns.oid = dst.relnamespace
    WHERE con.contype = 'f' AND src_ns.nspname = ANY($1)
    ORDER BY 1, 2`,
  [SCHEMAS],
);
const { rows: [{ count: migrations }] } = await client.query('SELECT count(*)::int AS count FROM meta.schema_migrations');
await client.end();

const fkColumns = new Set(fks.flatMap((f) => f.cols.split(', ').map((col) => `${f.src_schema}.${f.src_table}.${col}`)));
const keys = (c) => {
  const k = [c.is_pk && 'PK', fkColumns.has(`${c.table_schema}.${c.table_name}.${c.column_name}`) && 'FK'].filter(Boolean);
  return k.length ? ` ${k.join(', ')}` : '';
};
const typeOf = (c) => (c.data_type === 'ARRAY' ? `${c.udt_name.replace(/^_/, '')}_array` : c.udt_name).replace(/[^a-z0-9_]/gi, '_');
const entity = (table) => table.replace(/[^a-z0-9_]/gi, '_');

let md = `# Database ERD\n\n> Generated by \`npm run db:erd\` from the live database (${migrations} migrations applied). Do not edit by hand.\n>\n`;
md += '> Relationships drawn are real foreign keys inside a schema. Ids that point into another service\'s schema\n';
md += '> (e.g. `payments.payments.transfer_id` → `core.transfers.id`) are deliberately **not** foreign keys: each service owns its data\n';
md += '> and they are linked by id through APIs and events. See [database.md](database.md) for the rules.\n';

for (const schema of SCHEMAS) {
  const tables = [...new Set(columns.filter((c) => c.table_schema === schema).map((c) => c.table_name))];
  md += `\n## \`${schema}\` — ${OWNERS[schema]}\n\n\`\`\`mermaid\nerDiagram\n`;
  for (const t of tables) {
    md += `  ${entity(t)} {\n`;
    for (const c of columns.filter((x) => x.table_schema === schema && x.table_name === t)) {
      md += `    ${typeOf(c)} ${c.column_name}${keys(c)}${c.is_nullable === 'NO' && !c.is_pk ? ' "not null"' : ''}\n`;
    }
    md += '  }\n';
  }
  for (const fk of fks.filter((f) => f.src_schema === schema && f.dst_schema === schema && f.src_table !== f.dst_table)) {
    md += `  ${entity(fk.dst_table)} ||--o{ ${entity(fk.src_table)} : "${fk.cols}"\n`;
  }
  md += '```\n';
}

writeFileSync(join(ROOT, 'docs', 'database-erd.md'), md);
console.log(`Wrote docs/database-erd.md (${new Set(columns.map((c) => `${c.table_schema}.${c.table_name}`)).size} tables, ${fks.length} foreign keys).`);
