// Creates .env from .env.example, filling generated secrets, and writes JWT signing keys to secrets/.
// Usage: npm run setup:env -- --pg-superuser-password=<pw> [--force]
import { randomBytes, generateKeyPairSync } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { ROOT } from './lib/paths.mjs';

const args = Object.fromEntries(
  process.argv.slice(2).map((a) => {
    const [k, ...v] = a.replace(/^--/, '').split('=');
    return [k, v.length ? v.join('=') : true];
  }),
);

const envPath = join(ROOT, '.env');
if (existsSync(envPath) && !args.force) {
  console.error('.env already exists. Re-run with --force to regenerate it (all generated secrets will change).');
  process.exit(1);
}

const pgSuperPassword = args['pg-superuser-password'] ?? process.env.PG_SUPERUSER_PASSWORD;
if (!pgSuperPassword) {
  console.error('Missing --pg-superuser-password=<password of the "postgres" user>.');
  process.exit(1);
}

const secret = () => randomBytes(24).toString('base64url');
const key32 = () => randomBytes(32).toString('base64');

const template = readFileSync(join(ROOT, '.env.example'), 'utf8');
const output = template
  .replace(/^# Copy with.*\n(# .*\n)*# Never put real secrets in this file\.\n/m, '# Generated by scripts/setup-env.mjs — local secrets, do not commit.\n')
  .replace(/__GENERATE_KEY32__/g, () => key32())
  .replace(/__GENERATE__/g, () => secret())
  .replace('__ASK__', pgSuperPassword);

writeFileSync(envPath, output, { mode: 0o600 });

const secretsDir = join(ROOT, 'secrets');
mkdirSync(secretsDir, { recursive: true });
const { privateKey, publicKey } = generateKeyPairSync('rsa', {
  modulusLength: 2048,
  publicKeyEncoding: { type: 'spki', format: 'pem' },
  privateKeyEncoding: { type: 'pkcs8', format: 'pem' },
});
writeFileSync(join(secretsDir, 'jwt-private.pem'), privateKey, { mode: 0o600 });
writeFileSync(join(secretsDir, 'jwt-public.pem'), publicKey);

console.log('Created .env and secrets/jwt-{private,public}.pem (both git-ignored).');
